RazorPagesProject/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPagesProject/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesProject.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPagesProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesProject/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using RazorPagesProject.Data;
using RazorPagesProject.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IQuoteService _quoteService;
        private readonly ApplicationDbContext _db;

        public IndexModel(ILogger<IndexModel> logger, IQuoteService quoteService, ApplicationDbContext db)
        {
            _logger = logger;
            _quoteService = quoteService;
            _db = db;
        }

        [BindProperty]
        public Message Message { get; set; }

        [TempData]
        public string MessageAnalysisResult { get; set; }

        public string Quote { get; private set; }

        public IList<Message> Messages { get; private set; }
        public async Task OnGetAsync()
        {
            Messages = await _db.GetMessagesAsync();
            Quote = await _quoteService.GenerateQuote();
        }
        public async Task<IActionResult> OnPostDeleteMessageAsync(int id)
        {
            await _db.DeleteMessageAsync(id);

            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostDeleteAllMessagesAsync()
        {
            await _db.DeleteAllMessagesAsync();

            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostAddMessageAsync()
        {
            if (!ModelState.IsValid)
            {
                 Messages = await _db.GetMessagesAsync();
              
                return Page();
            }

            await _db.AddMessageAsync(Message);

            return RedirectToPage();
        }


        public async Task<IActionResult> OnPostAnalyzeMessagesAsync()
        {
            Messages = await _db.GetMessagesAsync();
        
          
            if (Messages.Count == 0)
            {
                MessageAnalysisResult = "There are no messages to analyze.";
            }
            else
            {
                var wordCount = 0;

                foreach (var message in Messages)
                {
                    wordCount += message.Text.Split(' ').Length;
                }

                var avgWordCount = Decimal.Divide(wordCount, Messages.Count);
                MessageAnalysisResult = $"The average message length is {avgWordCount:0.##} words.";
            }

            return RedirectToPage();
        }
    }
}

RazorPagesProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesProject/Pages/About.cshtml
@page
@model RazorPagesProject.Pages.AboutModel
@{
}

RazorPagesProject/Pages/Contact.cshtml
@page
@model RazorPagesProject.Pages.ContactModel
@{
}

RazorPagesProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Message System";
}


<h1>@ViewData["Title"]</h1>

<!-- <snippet_Quote> -->
<input id="quote" type="hidden" value="@Model.Quote">
<!-- </snippet_Quote> -->

<form id="addMessage" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Add a message</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label asp-for="Message.Text"></label>
                <input asp-for="Message.Text" class="form-control" style="width:100%">
                <span asp-validation-for="Message.Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button id="addMessageBtn" type="submit" asp-page-handler="AddMessage" class="btn btn-default">Add Message</button>
            </div>
        </div>
    </div>
</form>
<form id="messages" method="post">
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <button id="deleteAllBtn" type="submit" asp-page-handler="DeleteAllMessages" class="pull-right btn btn-danger">Clear All</button>
            <h3 class="panel-title" style="line-height:2.1">Messages</h3>
        </div>
        <div class="panel-body">
            <ul>
                @foreach (var message in Model.Messages)
                {
                    <li style="line-height:2.5">
                        <button id="deleteBtn@(message.Id)" type="submit" class="btn btn-danger" style="margin-bottom:2px" asp-page-handler="DeleteMessage" asp-route-id="@message.Id">Delete</button>
                        @message.Text
                    </li>
                }
            </ul>
        </div>
    </div>
</form>

<form id="analyze" method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Analyze Messages</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <button id="analyzeBtn" type="submit" asp-page-handler="AnalyzeMessages" class="btn btn-default">Analyze</button>
            </div>
            <div class="form-group">
                @Model.MessageAnalysisResult
            </div>
        </div>
    </div>
</form>

RazorPagesProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPagesProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPagesProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RazorPagesProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>